export const projects = [
  {
    title: 'Look your Song',
    description: "in this project you can search for songs and information about your favorite musicians and bands",
    image: '/images/looksong.jpg',
    tags: ['Javascript','React', 'API'],
    language: 'Spanish',
    visit: 'https://lookyoursong.netlify.app/',
    code: 'https://github.com/tomashoffer/band-songs',
    id: 0,
  },
  {
    title: 'Quote Crypto',
    description:"In this project you can see the current values of the 10 most important cryptocurrencies such as Bitcoin, ETH, XRP ... You can obtain the values in different currencies.",
    image: '/images/crypto.jpg',
    tags: ['Javascript', 'React', 'API'],
    language: 'Spanish',
    visit: 'https://cryptoquoteapp.netlify.app/',
    code: 'https://github.com/tomashoffer/cryptoquoter',
    id: 1,
  },
  {
    title: 'Image Bank',
    description: "This is an app where you can search for images of what you want! Thanks to an API you can use these photos for your own projects.",
      image: '/images/imgbank.jpg',
      tags: ['Javascript', 'React', 'API'],
      language: 'Spanish',
    visit: 'https://imagesbank.netlify.app/',
    code: 'https://github.com/tomashoffer/buscadorimagenes',
    id: 2,
  },
  {
    title: 'Unichat',
    description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    image: '/images/4.jpg',
    tags: ['React', 'ChatEngine', 'Firebase'],
    language: 'Spanish',
    visit: 'https://google.com',
    code: 'https://google.com',
    id: 3,
  },
];

// export const TimeLineData = [
//   { year: 2017, text: 'Started my journey', },
//   { year: 2018, text: 'Worked as a freelance developer', },
//   { year: 2019, text: 'Founded JavaScript Mastery', },
//   { year: 2020, text: 'Shared my projects with the world', },
//   { year: 2021, text: 'Started my own platform', },
// ];